### PR TITLE
create pid file if does not exist

### PR DESCRIPTION
**Pull request by pxlpnk**
it now creates the pidfile if it does not exist, otherwise it opens it with r+ and reads the pid

### CODE REVIEW

**Comment by abangratz** [comment]
Rejected. mode "r+" creates the file.

**Comment by pxlpnk** [comment]
No it doesn't 

<pre>
 f = File.open("test", "r+")
Errno::ENOENT: No such file or directory - test
    from (irb):3:in `initialize'
    from (irb):3:in `open'
    from (irb):3
    from /home/at/.rvm/rubies/ruby-1.9.3-p392/bin/irb:16:in `<main>'
</pre>

From the docs:

<pre>
"r+" Read-write, starts at beginning of file.
</pre>

**Comment by abangratz** [comment]
I'll fix it, there's still a way without all the 'ifs'

**Comment by abangratz** [comment]
Should be good now.

**Comment by pxlpnk** [comment]
thanks. i like the solution!  (:

**Pull request closed without merging**
